Faster version of transWhere and checking for multiple joins
rainlab/translate-plugin pull request #586
Opened 2020-06-24 08:43 UTC by mterman

Added scope TransWhereSpecificLocale that uses where clause on only specified locale and not default locale and selected locale. I think that this is a more common use case for the transWhere and it is much faster.
This addresses the issue: https://github.com/rainlab/translate-plugin/issues/581

Also in this pull request, I added checking for multiple joins to the translation index table. With these changes, it is now possible to chain multiple transWhere clauses, also with multiple transWhereSpecificLocale and transOrderBy. It is also possible to mix locales in different clauses.

Please feel free to change name of the TransWhereSpecificLocale to something shorter.

2020-07-05 15:47 UTC, mjauvin commented
@aurelien-roy what do you think about this proposed change?

2020-07-07 08:41 UTC, aurelien-roy commented
@mjauvin This approach looks good to me! Nice way of solving the multi-join issue.

Could bug fix #587 be included in this too?

2020-07-07 09:43 UTC, mterman commented
I think that this would be a solution to both problems.

$indexTableAlias = 'rainlab_translate_indexes_' . $locale;

should be changed to:

$indexTableAlias = 'rainlab_translate_indexes_' . $index . '_' . $locale;

Then join method should look like this:

protected function joinTranslateIndexesTable($query, $locale, $indexTableAlias, $index)
{
        $joinTableWithAlias = 'rainlab_translate_indexes as ' . $indexTableAlias;
        // check if table with same name and alias is already joined
        if (collect($query->getQuery()->joins)->contains('table', $joinTableWithAlias)) {
            return $query;
        }

        $query->leftJoin($joinTableWithAlias, function($join) use ($locale, $indexTableAlias, $index) {
            $join
                ->on(Db::raw(DbDongle::cast($this->model->getQualifiedKeyName(), 'TEXT')), '=', $indexTableAlias . '.model_id')
                ->where($indexTableAlias . '.model_type', '=', $this->getClass())
                ->where($indexTableAlias . '.item', '=', $index)
                ->where($indexTableAlias . '.locale', '=', $locale)
            ;
        });

        return $query;
}

2020-07-11 13:12 UTC, mjauvin commented
@mterman can you update your PR to do this?

2020-07-22 11:28 UTC, mterman commented
@mjauvin I updated the PR.
I tested this code on a medium set of data ~69k rows in rainlab_translate_indexes. 3 locales are active.
The example below is relatively slow but it is usable.
`$query->transWhereSpecificLocale('title', '%test%', 'en', 'LIKE')->transOrderBy('title', 'asc', 'de')`

2020-11-05 17:00 UTC, mariavilaro commented
Hi! Just wanted to say that I hit this problem (and 587), I applied this pull request and everything works like a charm. When do you think that you will publish it? Thank you!

2020-11-05 17:10 UTC, mjauvin commented
I need people to test this and also stats to show before/after perfs. Also need a better naming for this.

2020-11-05 18:21 UTC, mjauvin commented
I need people to test this and also stats to show before/after perfs. Also need a better naming for this.

2020-11-06 08:23 UTC, mariavilaro commented
The test worked for me. I can't help you with the perfs because my database are small. What do you mean with the better naming?

2020-11-06 13:08 UTC, mjauvin commented
@mariavilaro you can't provide details like number of records for the Rainlab.Translate tables and the time it takes for the queries before and after applying this PR?

2020-11-07 17:06 UTC, mjauvin commented
@mterman @aurelien-roy can you guys also provide for performance metrics before/after this PR is applied?

2020-11-07 17:32 UTC, mariavilaro commented
My rainlab_translate_indexes table has only 95 rows right now. I did some tests before and after PR and these are the results (I did the same tests with and without applying the PR changes and ran each test 5 times). I can't really see a difference.

![imagen](https://user-images.githubusercontent.com/10522884/98447711-5cd77f80-2127-11eb-9de6-39f9d989b7af.png)

2020-11-07 17:50 UTC, mjauvin commented
@mariavilaro what are you saying, that the PR makes no difference?

2020-11-07 21:31 UTC, LukeTowers commented
@acasar could you try running some performance tests on this PR on your dataset as reported in #581

2020-11-09 14:24 UTC, mjauvin requested changes
@mterman can you create a class method that generates `$indexTableAlias` and use it instead of duplicating this code in multiple places?

2020-11-09 14:24 UTC, mjauvin commented on behaviors/TranslatableModel.php
>       * Applies a translatable index to a basic query. This scope will join the index
```suggestion
     * Applies a translatable index to a basic query. This scope will join the index table.
```

2020-11-09 14:24 UTC, mjauvin commented on behaviors/TranslatableModel.php
>       * Applies a sort operation with a translatable index to a basic query. This scope will join the index
```suggestion
     * Applies a sort operation with a translatable index to a basic query. This scope will join the index table.
```

2020-11-12 10:05 UTC, acasar commented
> @acasar could you try running some performance tests on this PR on your dataset as reported in #581

@LukeTowers I ran some tests and I can confirm that this PR vastly improves the situation. In my case using ``transWhere`` still takes around 60 seconds, but switching it to ``transWhereSpecificLocale`` completes in under 6ms - a 10000x improvement 👍 

My suggestion would even be to completely replace ``transWhere`` implementation with the new one, since I don't see the use for the original (slow) implementation any more.

2020-11-12 10:22 UTC, mterman commented
> @mterman can you create a class method that generates `$indexTableAlias` and use it instead of duplicating this code in multiple places?

I was busy this week and will bi away for the weekend.
Next week I can add requested changes, and do some tests and benchmarks.

2020-11-12 12:27 UTC, mjauvin commented
@mterman can you confirm if transWhereSpecificLocale() can be a replacement for transWhere()?

2020-11-12 12:29 UTC, mjauvin commented
@acasar how many records do you have for those numbers?

2020-11-12 12:40 UTC, acasar commented
> @acasar how many records do you have for those numbers?

Not as many .. around 7k in the base table and 14k in ``rainlab_translate_indexes``. In my experience ``whereTrans`` becomes very slow very quickly, that's why I suggest replacing the original implementation with the new one, unless of course there is a valid reason not to do it.

2020-11-12 14:02 UTC, mjauvin commented on behaviors/TranslatableModel.php
> +     * Applies a translatable index to a basic query. This scope applies only to specific locale. This scope will join the index
```suggestion
     * Applies a translatable index to a basic query. This scope applies only to specific locale. This scope will join the index table.
```

2020-11-12 14:25 UTC, mterman commented
> @mterman can you confirm if transWhereSpecificLocale() can be a replacement for transWhere()?

It's possible, it won't break anything as in code will run and it will pass tests. But expected behaviour will change for the people who are expecting it to look both in the default and selected locale.

2020-11-12 14:43 UTC, mjauvin commented
> > @mterman can you confirm if transWhereSpecificLocale() can be a replacement for transWhere()?
> 
> It's possible, it won't break anything as in code will run and it will pass tests. But expected behaviour will change for the people who are expecting it to look both in the default and selected locale.

Can you elaborate a bit more on this?

2020-11-12 15:19 UTC, mjauvin commented
@mterman Ok, so if I understand correctly, 'scopeTransWhereSpecificLocale()` does not use the fallback translation if no translation is found for the requested locale, correct?

2020-11-12 16:28 UTC, LukeTowers commented
> I suggest replacing the original implementation with the new one, unless of course there is a valid reason not to do it.

@acasar whenever we're evaluating changes for performance sake they must be validated to not change existing behaviour in any breaking way, and we also need benchmarks to prove that the change actually improves performance.

2020-11-12 18:37 UTC, mjauvin commented
I tested this and there is no fallback as I expected.

I almost exclusively use the transWhere() scope in situation where I want to find a model based on a slug (which is usually provided in a cms page :slug param) and as long as the slug has a translation, this new transWhereSpecificLocale() scope will do the job, but as soon as a slug only exists in the default language, that breaks if the page is opened in one of the other languages with that slug in the default language.

What am I missing?

2020-11-13 08:32 UTC, mterman commented
> @mterman Ok, so if I understand correctly, 'scopeTransWhereSpecificLocale()` does not use the fallback translation if no translation is found for the requested locale, correct?

Yes, that is correct.


> I tested this and there is no fallback as I expected.
> 
> I almost exclusively use the transWhere() scope in situation where I want to find a model based on a slug (which is usually provided in a cms page :slug param) and as long as the slug has a translation, this new transWhereSpecificLocale() scope will do the job, but as soon as a slug only exists in the default language, that breaks if the page is opened in one of the other languages with that slug in the default language.
> 
> In summary, if 'en' is the default locale and 'fr' is an alternate locale:
> 
> * transWhere('key', 'value', 'fr') will return records that have key==value in the FR locale  OR fallback to records where key==value in EN locale
> * transWhereSpecificLocale('key', 'value', 'fr') will return records that have key==value in FR locale OR null
> 
> Personally, this is of no use to me as you would require another query to get the fallback record.
> 
> What am I missing?

You are not missing anything. That is the expected behaviour of the transWhereSpecificLocale scope. For me that is useful, we usually don't fallback to the default locale it some content is not available in selected locale.

As per your example, if there are no records in FR locale we will not show content in EN locale but go to 404 or redirect to homepage.

2020-11-13 08:57 UTC, mariavilaro commented
Maybe, instead of adding a new scope "transWhereSpecificLocale", we could just add a new param $fallbackToDefaultLocale (default true,so we don't introduce a breaking change) to transWhere to say if we want to fallback to the default locale or not:

Classic transWhere with fallback:
transWhere('key', 'value', 'fr', '=') 

New transWhere without fallback that can use the new code:
transWhere('key', 'value', 'fr', '=', false) 

I think that other laravel translation libraries do it like this.

2020-11-13 09:56 UTC, acasar commented
To preserve the original fallback behavior I made an alternative suggestion here: https://github.com/rainlab/translate-plugin/pull/623

2020-11-15 13:30 UTC, mjauvin commented
@mterman would you mind updating this to keep the scopeTransOrderBy() changes, remove the changes to scopeTransWhere() and drop scopeTransWhereSpecificLocale?

Thanks.

2020-11-16 07:35 UTC, LukeTowers commented
@mjauvin are you planning on merging both?

2020-11-16 13:05 UTC, mjauvin commented
@LukeTowers yes, but this one only for the transOrderBy changes.

2020-11-16 19:24 UTC, mjauvin commented
@mterman if you could make the requested changes, I'd like to merge this for upcoming 1.7.4. I'd like to make the release today or tomorrow.

Thanks.

2020-11-16 22:21 UTC, mjauvin approved these changes

2020-11-16 22:21 UTC, mjauvin commented
Thanks @mterman, can you pull changes from master in your branch? Tests have been fixed in latest master.

@aurelien-roy can you retest this to make sure it works as expected?

Thanks guys!

2020-11-17 11:35 UTC, mjauvin commented
@mterman please pull latest changes for the upstream master branch before merging, looks like you didn't.

2020-11-17 12:21 UTC, mterman commented
> @mterman please pull latest changes for the upstream master branch before merging, looks like you didn't.

Is this the correct upsteram url? And have I been merging from the right branch?

```
% git checkout specific_where_and_joins                                                                                                                                                                 
Already on 'specific_where_and_joins'
% git remote -v                                                                                                                                                                                         
origin	https://github.com/mterman/translate-plugin.git (fetch)
origin	https://github.com/mterman/translate-plugin.git (push)
upstream	https://github.com/rainlab/translate-plugin.git (fetch)
upstream	https://github.com/rainlab/translate-plugin.git (push)
% git merge upstream/master                                                                                                                                                                             
Already up to date.
% git push
Everything up-to-date
```

2020-11-17 12:37 UTC, mjauvin commented
@mterman I'm sorry, looks like this is good on your end... not sure why those tests are going through fine when using your branch locally, though... I'll find the problem and get back to you. How long until you're offline?

2020-11-17 13:06 UTC, mjauvin commented
Ok, I made a change to your repo to fix this, we're good now.

2020-11-17 13:12 UTC, merged